default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: image_development
  username: developer
  password: <%= ENV["password"] %>
  host: localhost

test:
  <<: *default
  database: image_test
  username: developer
  password: <%= ENV["password"] %>
  host: localhost

production:
  <<: *default
  database: image_production
  username: developer
  password: <%= ENV["password"] %>